# byctrl配置文件，需要放在调用进程或byctrl.dll同目录，调用进程一般情况下为主程序，文件编码utf-8
# #开头的行为注释

# 是否使用独立通道朗读，0读屏通道，1独立通道
speak.useSlave = 1

# 朗读通道名称，仅当speak.useSlave = 1时有效
# 为空则使用共享三方通道，通道不存在会自动创建
speak.slaveName = 我的三方通道

# 是否始终排队朗读，为空时由开发者决定是否排队朗读，0始终打断朗读，1始终排队朗读，除非手动打断
speak.append = 0

# 朗读时是否允许被打断，0不允许打断，，1允许打断
speak.allowBreak = 1

# 是否启用任意键打断，0按下厨设置的打断剑以外都不打断朗读，1按下任何按键都打断朗读
anyKeyBreak = 0

# 日志文件路径，日志要写入哪个文件，可以为空，开发者的参数优先
logPath = 
